# buildspec.yaml
version: 0.2
phases:
  install:
    runtime-versions:
      #docker: 18
      java: corretto11
    commands:
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - mkdir ~/.kube
      #- aws eks --region ap-northeast-2 update-kubeconfig --name eks
      - aws eks --region ap-northeast-2 update-kubeconfig --name ecomarket-eks-cluster
      - aws eks update-kubeconfig --name ecomarket-eks-cluster
      #- kubectl get po -n ecomarket-eks-cluster
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/
  build:
    commands:
      - mvn clean package
      - echo Building the Docker image
      #- docker build -t $IMAGE_REPO_NAME:latest .
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG .
      #- docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - AWS_ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - DATE='date'
      - echo Build completed on $DATE
      - sed -i.bak 's#AWS_ECR_URI#'"$AWS_ECR_URI"'#' ./kubernetes/deployment.yml
      - sed -i.bak 's#DATE_STRING#'"$DATE"'#' ./kubernetes/deployment.yml
      - kubectl apply -f ./kubernetes/deployment.yml
      - kubectl apply -f ./kubernetes/service.yml

cache:
  paths:
    - '/root/.m2/**/*'