server:
  port: 8080

spring:
  datasource:
    #url: jdbc:h2://localhost:8082/review;
    #url: jdbc:h2:tcp://localhost/~/review;
    #username: sa
    #password:
    #driver-class-name: org.h2.Driver
    url: jdbc:mysql://ecomarket-review-db.cgcyiu667p2z.ap-northeast-2.rds.amazonaws.com:3306/ecomarket_review_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: kama8028
    password: godqhr0850!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect #로컬 삭제

---

spring:
  profiles: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9099
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: review
          destination: ecomarket
          contentType: application/json
        event-out:
          destination: ecomarket
          contentType: application/json

---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: review
          destination: ecomarket
          contentType: application/json
        event-out:
          destination: ecomarket
          contentType: application/json

server:
  port: 8080