apiVersion: v1
kind: Service
metadata:
  name: review-svc
  namespace: ecomarket
  labels:
    app: review
spec:
  ports:
    - port: 80
      targetPort: 8090
  selector:
    app: review
  type: NodePort